---
title: "Code"
author: "Lorenzo Ricolfi"
date: "2024-03-27"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Loading packages
```{r}
#devtools::install_github("EIvimeyCook/ShinyDigitise")
library(tidyr)
library(dplyr)
library(here)
library(sandwich)
library(data.table)
library(metaDigitise)
#library(shinyDigitise)
```

# Raw data extracion - MetaDigitise
```{r}
dat <- metaDigitise("~/PhD/GitHub/PFAS_Trophic_Magnification/metaDigitise")
dat <- shinyDigitise("~/PhD/GitHub/PFAS_Trophic_Magnification/metaDigitise")
#write.csv(dat, file = "metaDigitise/MetaDigitise_Cara_2022_3r.csv")
```

# Data wrangling
```{r}
raw_data <- read.csv(here("metaDigitise/Raw_data.csv"))
head(raw_data)
wide_data <- raw_data %>%
  pivot_wider(
    names_from = variable,
    values_from = c(mean, sd),
    names_glue = "{variable}_{.value}"
  )
head(wide_data)
```

## Cara_2022
```{r}
Cara_2022 <- wide_data %>% 
  filter(Study_ID == "S_052") %>%
  setDT() %>% 
  melt(id.vars = c("group_id"), na.rm = TRUE) %>% 
  dcast(group_id ~ variable, value.var = "value", fun.aggregate = max, na.rm = TRUE) %>% 
  mutate(group_id = gsub("^(\\w+\\s[^,]+)", "\\1,", group_id)) %>% 
  separate(group_id, into = c("PFAS", "species", "location"), sep = ",\\s*", extra = "drop")

Cara_2022_loc4 <- Cara_2022 %>% 
  filter(location == "location 4") %>%
  mutate(across(ends_with("mean") | ends_with("sd"), ~ as.numeric(as.character(.)))) %>% 
  mutate(log_PFOA_mean = log(PFOA_mean)) %>%
  select_if(~ !all(is.na(.)))

#write.csv(Cara_2022_loc4, file = here("Rdata", "Cara_2022_loc4.csv"))

Cara_2022_loc5 <- Cara_2022 %>% 
  filter(location == "location 5") %>%
  mutate(across(ends_with("mean") | ends_with("sd"), ~ as.numeric(as.character(.))))

#write.csv(Cara_2022_loc5, file = here("Rdata", "Cara_2022_loc5.csv"))

Cara_2022_loc8 <- Cara_2022 %>% 
  filter(location == "location 8") %>%
  mutate(across(ends_with("mean") | ends_with("sd"), ~ as.numeric(as.character(.))))

#write.csv(Cara_2022_loc8, file = here("Rdata", "Cara_2022_loc8.csv"))
```

## Martin_2004
```{r}
Martin_2004 <- wide_data %>% 
  filter(Study_ID == "S_013") %>%
  select_if(~ !all(is.na(.))) %>% 
  setDT() %>% 
  melt(id.vars = c("group_id"), na.rm = TRUE) %>% 
  dcast(group_id ~ variable, value.var = "value", fun.aggregate = max, na.rm = TRUE) %>% 
  mutate(group_id = gsub("^(\\w+\\s[^,]+)", "\\1,", group_id)) %>% 
  separate(group_id, into = c("PFAS", "species", "food_web"), sep = ",\\s*", extra = "drop")

Martin_2004_pelagic <- Martin_2004 %>% 
  filter(food_web == "pelagic food web") %>%
  mutate(across(ends_with("mean") | ends_with("sd"), ~ as.numeric(as.character(.))))

#write.csv(Martin_2004_pelagic, file = here("Rdata", "Martin_2004_pelagic.csv"))

Martin_2004_benthic <- Martin_2004 %>% 
  filter(food_web == "benthic food web") %>%
  mutate(across(ends_with("mean") | ends_with("sd"), ~ as.numeric(as.character(.))))

#write.csv(Martin_2004_benthic, file = here("Rdata", "Martin_2004_benthic.csv"))
```

## Koch_2020
```{r}
Koch_2020 <- wide_data %>% 
  filter(Study_ID == "S_053") %>%
  select_if(~ !all(is.na(.))) %>% 
  setDT() %>% 
  melt(id.vars = c("group_id"), na.rm = TRUE) %>% 
  dcast(group_id ~ variable, value.var = "value", fun.aggregate = max, na.rm = TRUE)

#write.csv(Koch_2020, file = here("Rdata", "Koch_2020.csv"))
```

## Mazzoni_2020
```{r}
Mazzoni_2020 <- wide_data %>% 
  filter(Study_ID == "S_004") %>%
  select_if(~ !all(is.na(.)))
```

## Liu_2018
```{r}
Liu_2018 <- wide_data %>% 
  filter(Study_ID == "S_017") %>%
  select_if(~ !all(is.na(.)))
```

## Gao_2020
```{r}
Gao_2020 <- wide_data %>% 
  filter(Study_ID == "S_019") %>%
  select_if(~ !all(is.na(.)))
```

## Chen_2018
```{r}
Chen_2018 <- wide_data %>% 
  filter(Study_ID == "S_021") %>%
  select_if(~ !all(is.na(.)))
```

## Du_2021
```{r}
Du_2021 <- wide_data %>% 
  filter(Study_ID == "S_023") %>%
  select_if(~ !all(is.na(.)))
```

## Ren_2022
```{r}
Ren_2022 <- wide_data %>% 
  filter(Study_ID == "S_035") %>%
  select_if(~ !all(is.na(.)))
```

## Koch_2021
```{r}
Koch_2021 <- wide_data %>% 
  filter(Study_ID == "S_054") %>%
  select_if(~ !all(is.na(.)))
```

## Li_2008
```{r}
Li_2008 <- wide_data %>% 
  filter(Study_ID == "S_056") %>%
  select_if(~ !all(is.na(.)))
```

## Pan_2010
```{r}
Pan_2010 <- wide_data %>% 
  filter(Study_ID == "S_057") %>%
  select_if(~ !all(is.na(.)))
```

## Van de Vijver_2003
```{r}
Van_de_Vijver_2003 <- wide_data %>% 
  filter(Study_ID == "S_058") %>%
  select_if(~ !all(is.na(.)))
```

# Regression analysis

## Cara_2022
```{r}
# Location 4
Cara_2022_loc4 <- read.csv(here("RData", "Cara_2022_loc4.csv"))
Cara_2022_loc4_PFOA_weights <- 1 / (Cara_2022_loc4$PFOA_sd^2)

Cara_2022_loc4_lm_model_PFOA <- lm(PFOA_mean ~ TL_mean, 
                                   data = Cara_2022_loc4,
                                   weights = Cara_2022_loc4_PFOA_weights)

plot(residuals(Cara_2022_loc4_lm_model_PFOA))

coeftest(Cara_2022_loc4_lm_model_PFOA, vcov. = vcovHC)

#Location 5
Cara_2022_loc5 <- read.csv(here("RData", "Cara_2022_loc5.csv"))

Cara_2022_loc5_PFOA_weights <- 1 / (Cara_2022_loc5$PFOA_sd^2)
Cara_2022_loc5_PFUnDA_weights <- 1 / (Cara_2022_loc5$PFUnDA_sd^2)

Cara_2022_loc5_lm_model_PFOA <- lm(PFOA_mean ~ TL_mean, 
                                   data = Cara_2022_loc5,
                                   weights = Cara_2022_loc5_PFOA_weights)
summary(Cara_2022_loc5_lm_model_PFOA)

Cara_2022_loc5_lm_model_PFUnDA <- lm(PFUnDA_mean ~ TL_mean, 
                                     data = Cara_2022_loc5, 
                                     weights = Cara_2022_loc5_PFUnDA_weights)
summary(Cara_2022_loc5_lm_model_PFUnDA)

#Location 8
Cara_2022_loc8 <- read.csv(here("RData", "Cara_2022_loc8.csv"))

Cara_2022_loc8_PFOA_weights <- 1 / (Cara_2022_loc8$PFOA_sd^2)
Cara_2022_loc8_PFTrDA_weights <- 1 / (Cara_2022_loc8$PFTrDA_sd^2)

Cara_2022_loc8_lm_model_PFOA <- lm(PFOA_mean ~ TL_mean, 
                                   data = Cara_2022_loc8,
                                   weights = Cara_2022_loc8_PFOA_weights)
summary(Cara_2022_loc8_lm_model_PFOA)

Cara_2022_loc5_lm_model_PFTrDA <- lm(PFTrDA_mean ~ TL_mean, 
                                     data = Cara_2022_loc8, 
                                     weights = Cara_2022_loc8_PFTrDA_weights)
summary(Cara_2022_loc5_lm_model_PFTrDA)
```

## Martin_2004
```{r}
Martin_2004_pelagic <- read.csv(here("RData", "Martin_2004_pelagic.csv"))
Martin_2004_pelagic_lm_model_PFOS <- lm(ln_PFOS_mean ~ TL_mean, 
                                   data = Martin_2004_pelagic)
summary(Martin_2004_pelagic_lm_model_PFOS)


Martin_2004_benthic <- read.csv(here("RData/Martin_2004_benthic.csv"))
Martin_2004_benthic_lm_model_PFOS <- lm(ln_PFOS_mean ~ TL_mean, 
                                   data = Martin_2004_benthic)
summary(Martin_2004_benthic_lm_model_PFOS)
```

## Koch_2020
```{r}
Koch_2020 <- read.csv(here("Rdata", "Koch_2020.csv"))
Koch_2020_lm_model_PFOS <- lm(PFOS_mean ~ )
```

## Mazzoni_2020
```{r}

```

## Liu_2018
```{r}

```

## Gao_2020
```{r}

```

## Chen_2018
```{r}

```

## Du_2021
```{r}

```

## Ren_2022
```{r}

```

## Koch_2021
```{r}

```

## Li_2008
```{r}

```

## Pan_2010
```{r}

```

## Van de Vijver_2003
```{r}

```
